# Generated by Django 4.1.5 on 2023-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicefinder', '0003_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='profile_img',
            field=models.ImageField(default='', upload_to='media/profile'),
        ),
    ]
