# Generated by Django 4.1.5 on 2023-04-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicefinder', '0004_alter_partner_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
    ]
