# Generated by Django 4.1.5 on 2023-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicefinder', '0005_partner_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='timing',
            field=models.CharField(default='', max_length=50),
        ),
    ]
