# Generated by Django 4.1.5 on 2023-04-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicefinder', '0006_partner_address_partner_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('f_time', models.TimeField()),
                ('a_time', models.TimeField()),
                ('description', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicefinder.userdetail')),
            ],
        ),
    ]
