# Generated by Django 4.1.5 on 2023-04-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicefinder', '0008_booking_bookingdate_booking_bookingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='servicer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='servicefinder.partner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='False', max_length=20),
        ),
    ]
