# Generated by Django 4.1.5 on 2023-04-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicefinder', '0010_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('profile_img', models.ImageField(default='', upload_to='media/profile')),
                ('aadhar', models.IntegerField()),
                ('address', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicefinder.userdetail')),
            ],
        ),
    ]
