# Generated by Django 4.1.5 on 2023-04-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicefinder', '0013_alter_booking_servicer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBookings',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('p_username', models.CharField(max_length=50)),
                ('cancel', models.BooleanField(default=False)),
                ('confirm', models.BooleanField(default=False)),
                ('Booking_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicefinder.booking')),
            ],
        ),
    ]
