# Generated by Django 4.1.5 on 2023-04-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicefinder', '0014_partnerbookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mapurl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
